# Generated by Django 4.1.1 on 2022-09-12 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('ChannelId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('chat_name', models.CharField(max_length=100)),
                ('chat_admin', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
