# Generated by Django 4.1.1 on 2022-09-12 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STEP',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('next_step', models.CharField(default='', max_length=20)),
                ('state', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='ChannelId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
