# Generated by Django 4.1.1 on 2022-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_step_alter_channel_channelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
