# Generated by Django 4.1.1 on 2022-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_step_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='chat_name',
            field=models.CharField(default='my Channell', max_length=100),
        ),
    ]
